# Generated by Django 6.0.2 on 2026-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
