# Generated by Django 6.0.1 on 2026-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_amount_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
