# Generated by Django 6.0.2 on 2026-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_discount_amount_order_discount_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
