# Generated by Django 6.0.2 on 2026-09-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0028_candlevariant_height_in_candlevariant_length_in_and_more"),
        ("orders", "0008_order_shipping_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="The exact variant ordered. Null on rows created before this field existed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="candles.candlevariant",
            ),
        ),
    ]
