# Generated by Django 6.0.2 on 2026-10-02 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_backfill_orderitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_label",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
