# Generated by Django 6.0.2 on 2026-10-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderitem_discount_amount_orderitem_discount_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("paid_after_cancel", "Paid after the order was cancelled"),
                            (
                                "paid_after_refund",
                                "Paid again after the order was refunded",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("refunded", "Refunded automatically"),
                            (
                                "refund_failed",
                                "Refund FAILED — refund it by hand in Stripe",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=10)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_incidents",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
