# Generated by Django 6.0.2 on 2026-10-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_paymentincident"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="free_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Units on this line given free by buy-two-get-three.",
            ),
        ),
    ]
