# Generated by Django 6.0.2 on 2026-08-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0008_order_shipping_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("purchasing", "Purchasing"),
                            ("purchased", "Purchased"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rate_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "shippo_shipment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("carrier", models.CharField(blank=True, default="", max_length=80)),
                (
                    "service_level",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(blank=True, default="usd", max_length=10),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("label_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_test", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="shipping_sh_status_0644c6_idx"
                    ),
                    models.Index(
                        fields=["tracking_number"],
                        name="shipping_sh_trackin_af3d4f_idx",
                    ),
                ],
            },
        ),
    ]
