# Generated by Django 6.0.2 on 2026-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
