# Generated by Django 6.0.2 on 2026-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0002_candle_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candles/'),
        ),
    ]
