# Generated by Django 6.0.2 on 2026-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0003_candle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candle',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
