# Generated by Django 6.0.1 on 2026-02-20 19:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0004_candle_stock_qty_alter_candle_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
