# Generated by Django 6.0.1 on 2026-02-26 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0005_alter_candle_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="candle",
            name="is_bestseller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candle",
            name="is_sold_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candle",
            name="collections",
            field=models.ManyToManyField(blank=True, related_name="candles", to="candles.collection"),
        ),
    ]