# Generated by Django 6.0.1 on 2026-02-27 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0006_collection_and_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candle',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='candles', to='candles.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='All candles', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='all-candles', max_length=140, unique=True),
        ),
    ]
