# Generated by Django 6.0.1 on 2026-02-27 02:13

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0007_collection_is_group_alter_candle_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='candles.candle')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
