# Generated by Django 6.0.1 on 2026-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0009_alter_candle_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('new_shopper', 'New shopper'), ('discount', 'Discount'), ('buy_1_get_2', 'Buy 1 get 2'), ('holiday', 'Holiday offer'), ('loyalty', 'Loyalty')], default='discount', max_length=40)),
                ('badge_text', models.CharField(max_length=60)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('apply_globally', models.BooleanField(default=False)),
                ('requires_login', models.BooleanField(default=False)),
                ('requires_no_orders', models.BooleanField(default=False)),
                ('candles', models.ManyToManyField(blank=True, related_name='promotions', to='candles.candle')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='candles.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='promotions', to='candles.collection')),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
    ]
