# Generated by Django 6.0.1 on 2026-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0010_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('badge_text', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('new_shopper', 'New shopper'), ('discount', 'Discount'), ('b1g2', 'Buy 1 get 2'), ('holiday', 'Holidays offer'), ('loyalty', 'Loyalty')], default='discount', max_length=30)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('new_shopper_only', models.BooleanField(default=False)),
                ('apply_globally', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candles', models.ManyToManyField(blank=True, related_name='direct_offers', to='candles.candle')),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='candles.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='offers', to='candles.collection')),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.AddField(
            model_name='candle',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='candles_m2m', to='candles.offer'),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
