# Generated by Django 6.0.1 on 2026-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0013_aboutgalleryitem_aboutreviewitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional final fixed price for discounted candles.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='new_shopper_days_active',
            field=models.PositiveSmallIntegerField(default=60, help_text='How many days after registration new shopper offer is valid.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='badge_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kind',
            field=models.CharField(choices=[('new_shopper', 'New shopper'), ('discount', 'Discount percent'), ('discounted_candles', 'Discounted candles'), ('b1g2', 'Buy 1 get 2'), ('holiday', 'Holiday offer'), ('loyalty', 'Loyalty')], default='discount', max_length=30),
        ),
    ]
