# Generated by Django 6.0.1 on 2026-03-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0014_offer_discounted_price_offer_new_shopper_days_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Example: 8 oz, 11.3 oz', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='candles.candle')),
            ],
            options={
                'unique_together': {('candle', 'size')},
            },
        ),
    ]
