# Generated by Django 6.0.1 on 2026-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0015_candlevariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candlevariant',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='candle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
