# Generated by Django 6.0.1 on 2026-04-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0016_alter_candlevariant_options_alter_candle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='base_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='fragrance_family',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candle',
            name='heart_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='ideal_spaces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='intensity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candle',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='season_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='top_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='use_case_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
