# Generated by Django 6.0.1 on 2026-05-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0017_candle_base_notes_candle_fragrance_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candle',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candle',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candle',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candle',
            name='short_description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='short_description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='short_description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='short_description_ru',
            field=models.TextField(blank=True, default=''),
        ),
    ]
