# Generated by Django 6.0.1 on 2026-05-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0018_candle_description_en_candle_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='short_description_fr',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='short_description_ru',
        ),
    ]
