# Generated by Django 6.0.1 on 2026-05-04 16:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0019_remove_candle_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('content_type', models.CharField(choices=[('gallery', 'Gallery'), ('review', 'Review')], default='gallery', max_length=20)),
                ('media', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media')),
                ('preview_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='preview_image')),
                ('caption', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sort_order', '-id'),
            },
        ),
        migrations.DeleteModel(
            name='AboutGalleryItem',
        ),
        migrations.DeleteModel(
            name='AboutReviewItem',
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='candle',
            name='base_notes',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='fragrance_family',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='heart_notes',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='ideal_spaces',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='mood_tags',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='season_tags',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='top_notes',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='use_case_tags',
        ),
        migrations.RemoveField(
            model_name='candlevariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='apply_globally',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='new_shopper_days_active',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='new_shopper_only',
        ),
        migrations.AlterField(
            model_name='candle',
            name='collections',
            field=models.ManyToManyField(blank=True, to='candles.collection'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='offers',
            field=models.ManyToManyField(blank=True, to='candles.offer'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candlevariant',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='candles',
            field=models.ManyToManyField(blank=True, to='candles.candle'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='candles.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='collections',
            field=models.ManyToManyField(blank=True, to='candles.collection'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kind',
            field=models.CharField(choices=[('new_shopper', 'New shopper'), ('discount', 'Discount percent'), ('b1g2', 'Buy 1 get 2'), ('holiday', 'Holiday offer'), ('loyalty', 'Loyalty')], max_length=30),
        ),
    ]
