# Generated by Django 6.0.1 on 2026-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0020_galleryitem_delete_aboutgalleryitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candlevariant',
            options={},
        ),
        migrations.AddField(
            model_name='offer',
            name='new_shopper_days_active',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='offer',
            name='new_shopper_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
    ]
