# Generated by Django 6.0.1 on 2026-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0021_alter_candlevariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='apply_globally',
            field=models.BooleanField(default=False),
        ),
    ]
