# Generated by Django 6.0.1 on 2026-05-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0022_offer_apply_globally'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='base_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='fragrance_family',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candle',
            name='heart_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='ideal_spaces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='intensity',
            field=models.CharField(blank=True, choices=[('soft', 'Soft'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=20),
        ),
        migrations.AddField(
            model_name='candle',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='season_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='top_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candle',
            name='use_case_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
