# Generated by Django 6.0.1 on 2026-08-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0023_candle_base_notes_candle_fragrance_family_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="kind",
            field=models.CharField(
                choices=[
                    ("new_shopper", "New shopper"),
                    ("discount", "Discount percent"),
                    ("b2g3", "Buy 2 get 3"),
                    ("holiday", "Holiday offer"),
                    ("loyalty", "Loyalty"),
                ],
                max_length=30,
            ),
        ),
    ]
