# Generated by Django 6.0.1 on 2026-08-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0024_alter_offer_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("hex", models.CharField(help_text="#RRGGBB", max_length=7)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Fragrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="candle",
            name="size",
            field=models.CharField(blank=True, help_text='e.g. "8 oz"', max_length=50),
        ),
        migrations.AddField(
            model_name="category",
            name="allows_wax_color",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candle",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candles",
                to="candles.color",
            ),
        ),
        migrations.AddField(
            model_name="candle",
            name="fragrance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candles",
                to="candles.fragrance",
            ),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fragrance__isnull", False)),
                fields=("fragrance", "size"),
                name="unique_fragrance_size",
            ),
        ),
    ]
