# Generated by Django 6.0.1 on 2026-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0025_color_fragrance_candle_size_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candle",
            name="unique_fragrance_size",
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fragrance__isnull", False)),
                fields=("fragrance", "size", "color"),
                name="unique_fragrance_size_color",
            ),
        ),
    ]
