# Generated by Django 6.0.1 on 2026-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0026_remove_candle_unique_fragrance_size_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candle",
            name="unique_fragrance_size_color",
        ),
        migrations.RemoveField(
            model_name="color",
            name="slug",
        ),
        migrations.AddField(
            model_name="offer",
            name="show_badge",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.UniqueConstraint(
                fields=("name", "size", "color"), name="unique_name_size_color"
            ),
        ),
        migrations.RemoveField(
            model_name="candle",
            name="fragrance",
        ),
        migrations.DeleteModel(
            name="Fragrance",
        ),
    ]
