# Generated by Django 6.0.2 on 2026-08-31 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0027_remove_candle_unique_fragrance_size_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candlevariant",
            name="height_in",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("4.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="candlevariant",
            name="length_in",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="candlevariant",
            name="weight_oz",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.00"),
                help_text="Вес одной штуки в унциях, без упаковки",
                max_digits=7,
            ),
        ),
        migrations.AddField(
            model_name="candlevariant",
            name="width_in",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.00"), max_digits=6
            ),
        ),
    ]
