# Generated by Django 6.0.1 on 2026-10-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candles", "0028_candlevariant_height_in_candlevariant_length_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="reward_candles",
            field=models.ManyToManyField(
                blank=True, related_name="reward_offers", to="candles.candle"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="reward_categories",
            field=models.ManyToManyField(
                blank=True, related_name="reward_offers", to="candles.category"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="reward_collections",
            field=models.ManyToManyField(
                blank=True, related_name="reward_offers", to="candles.collection"
            ),
        ),
    ]
